### ISSUE TITLE
help,please 

### ISSUE THREAD

**Issue by chongfaqin** [kang205/SASRec#11]
line 199 of modules.py :  outputs *= query_masks # broadcasting. (N, T_q, C)
I think,is it outputs *= query_masks # broadcasting. (h*N, T_q, C)?

**Comment by pmixer** [comment]
Guess no tensor of shape (h*N, T_q, C) should appear in computation pipeline, just adding few print function call to output `tf.shape` outputs would help you validate it, sorry for responding to a half-year ago's question :) @chongfaqin
