### ISSUE TITLE
Application for adding third-party re-implemenation link on README

### ISSUE THREAD

**Issue by pmixer** [kang205/SASRec#16]
Hi Team, @kang205 
I had prepared a PyTorch version of SASRec based on your tf implementation which behaves almost the same:

https://github.com/pmixer/SASRec.pytorch

could u pls consider adding the `Third-party Re-implementation` section like in https://github.com/wy1iu/LargeMargin_Softmax_Loss to let people know the work?

I hope to get the PyTorch implementation useful for wider audience and have someone help checking why it converges bit slower than tf implementation in model training  🤣 

Regards,
Zan

**Comment by kang205** [comment]
Sure, thanks a lot!
