### ISSUE TITLE
rank = predictions.argsort().argsort()[0] ?

### ISSUE THREAD

**Issue by feay1234** [kang205/SASRec#4]
https://github.com/kang205/SASRec/blob/641c378fcfac265ea8d1e5fe51d4d53eb892d1b4/util.py#L119

Why do you do argsort() twice?

https://github.com/kang205/SASRec/blob/641c378fcfac265ea8d1e5fe51d4d53eb892d1b4/util.py#L116

why do you multiply -1 to the prediction?

**Comment by Cliu2** [comment]
1. When you do 'argsort()' twice, you actually get an array storing the ranks of each elements in the original array, from smallest to largest.

2. By multiplying -1 to the original array, the original smallest value now become the largest value. Combining with the 'double argsort' trick, now you have the ranks from the largest to smallest.

**Comment by kang205** [comment]
> 1. When you do 'argsort()' twice, you actually get an array storing the ranks of each elements in the original array, from smallest to largest.
> 2. By multiplying -1 to the original array, the original smallest value now become the largest value. Combining with the 'double argsort' trick, now you have the ranks from the largest to smallest.

+1, thanks for the explanation.
