### ISSUE TITLE
Problem with num_batch

### ISSUE THREAD

**Issue by Nullees** [kang205/SASRec#6]
In your code, the num_batch is calculated by below way:
`num_batch = len(user_train) / args.batch_size`
But it could cause error in 
`for step in tqdm(range(num_batch), total=num_batch, ncols=70, leave=False, unit='b')`
Because 
> Traceback (most recent call last):
  File "main.py", line 61, in <module>
    for step in tqdm(range(num_batch), total=num_batch, ncols=70, leave=False, unit='b'):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by kang205** [comment]
It seems you’re using Py3, please try Py2 instead.

**Comment by Nullees** [comment]
Thanks for your suggestion~
