### ISSUE TITLE
Training checkpoint

### ISSUE THREAD

**Issue by agusgun** [kang205/SASRec#8]
Can you save the weight of the model (checkpoint) after some epochs?

**Comment by agusgun** [comment]
Another issue is I see in your paper that the minimum length of the training sequence is 5 meanwhile, in your implementation I see that it is 3

**Comment by kang205** [comment]
You may use TensorFlow's saver to export the model. As for the preprocessing of removing cold users and items, you should refer to [here](https://github.com/kang205/SASRec/blob/641c378fcfac265ea8d1e5fe51d4d53eb892d1b4/data/DataProcessing.py#L38).
